title: Isaac Delgado Aguilar
logo: /assets/img/headshot_circle.png
description: Welcome to my Data Science/ ML/ AI portfolio, feel free to check out all of my projects!
show_downloads: true
theme: jekyll-theme-minimal
